language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

before_script:
  - composer install
  - mkdir build

script:
  - composer grumphp

after_script:
  - php bin/coveralls -v
